# Generated by Django 4.2 on 2023-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='clients/avatars/', verbose_name='Аватар'),
        ),
    ]
