# Generated by Django 4.2 on 2023-06-30 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_match_client_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='from_client',
        ),
        migrations.RemoveField(
            model_name='match',
            name='to_client',
        ),
        migrations.AddField(
            model_name='match',
            name='client1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='client2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
